### ISSUE TITLE
Support async-profiler profile

### ISSUE THREAD

**Issue by ocadaruma** [moditect/jfr-analytics#16]
- As of now, jfr-analytics can't parse async-profiler's JFR output because of NPE when reading thread-group information
  * async-profiler doesn't embed thread-group info: https://github.com/async-profiler/async-profiler/blob/v2.9/src/jfrMetadata.cpp#L46-L50
- In the first place, RecordedThreadGroup in JFR is allowed to be null. We should handle the null case correctly
  * <img width="660" alt="image" src="https://github.com/moditect/jfr-analytics/assets/6070684/70935608-3f98-454b-a271-1a3380eeb571">

**Comment by gunnarmorling** [comment]
Fixed via #15
